
const data = [
    {
        id:"1",
        question:"",
        src:"../img/full/1.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    }
    ,{
        
        id:"2",
        question:"",
        src:"../img/full/2.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"2"
    },
    {
        id:"3",
        question:"",
        src:"../img/full/3.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },
    {
        id:"4",
        question:"",
        src:"../img/full/4.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },{
        id:"5",
        question:"",
        src:"../img/full/5.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },{
        id:"6",
        question:"",
        src:"../img/full/6.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"2"
    },{
        id:"7",
        question:"",
        src:"../img/full/7.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },{
        id:"8",
        question:"",
        src:"../img/full/8.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },{
        id:"9",
        question:"109)The parametric equations of a parabola are x = t^2 + 1, y=2t + 1.The cartesian equation of its directrix is",
        src:"",
        option1:"x + 1 = 0",
        option2:"y = 0",
        option3:"x = 0",
        option4:"y + 1 = 0",
        ansid:"3"
    },{
        id:"10",
        question:"",
        src:"../img/full/10.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"2"
    },{
        id:"11",
        question:"",
        src:"../img/full/11.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"4"
    },{
        id:"12",
        question:"",
        src:"../img/full/12.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },{
        id:"13",
        question:"",
        src:"../img/full/13.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },{
        id:"14",
        question:``,
        src:"../img/full/14.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },{
        id:"15",
        question:"",
        src:"../img/full/15.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"2"
    },{
        id:"16",
        question:"",
        src:"../img/full/16.png",
        option1:"(α − β)/200",
        option2:"α − β",
        option3:"(α − β)/100",
        option4:"β − α",
        ansid:"3"
    },{
        id:"17",
        question:"",
        src:"../img/full/17.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },{
        id:"18",
        question:"",
        src:"../img/full/18.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },{
        id:"19",
        question:"",
        src:"../img/full/19.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },{
        id:"20",
        question:"",
        src:"../img/full/20.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },{
        id:"21",
        question:"",
        src:"../img/full/21.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },{
        id:"22",
        question:"",
        src:"../img/full/22.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },{
        id:"23",
        question:"123)Joint equation of two lines, through (x1, y1), perpendicular to two lines ax^2 + 2hxy + by^2 = 0 , is",
        src:"../img/full/23.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"2"
    },{
        id:"24",
        question:"",
        src:"../img/full/24.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },{
        id:"25",
        question:"",
        src:"../img/full/25.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },{
        id:"26",
        question:"",
            src:"img/full/Screenshot_49.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"4"
    },
    {
        id:"27",
        question:"",
            src:"img/full/Screenshot_50.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"3"
    },
    {
        id:"28",
        question:"",
            src:"img/full/Screenshot_51.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"1"
    },
    {
        id:"29",
        question:"",
            src:"img/full/Screenshot_52.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"3"
    },
    {
        id:"30",
        question:"",
            src:"img/full/Screenshot_53.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"1"
    },
    {
        id:"31",
        question:"",
            src:"img/full/Screenshot_54.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"3"
    },
    {
        id:"32",
        question:"",
            src:"img/full/Screenshot_55.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"4"
    },
    {
        id:"33",
        question:"",
            src:"img/full/Screenshot_56.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"1"
    },
    {
        id:"34",
        question:"",
            src:"img/full/Screenshot_57.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"4"
    },
    {
        id:"35",
        question:"",
            src:"img/full/Screenshot_58.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"1"
    },
    {
        id:"36",
        question:"",
            src:"img/full/Screenshot_59.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"4"
    },
    {
        id:"37",
        question:"",
            src:"img/full/Screenshot_60.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"2"
    },
    {
        id:"38",
        question:"",
            src:"img/full/Screenshot_61.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"3"
    },
    {
        id:"39",
        question:"",
            src:"img/full/Screenshot_62.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"2"
    },
    {
        id:"40",
        question:"",
            src:"img/full/Screenshot_63.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"1"
    },
    {
        id:"41",
        question:"",
            src:"img/full/Screenshot_64.png",
            option1:"A",
            option2:"B",
            option3:"C",
            option4:"D",
            ansid:"4"
    },
    {
        id:"42",
        question:"",
        src:"img/full/Screenshot_65.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"2"
    },
    {
        id:"43",
        question:"",
        src:"img/full/Screenshot_66.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },
    {
        id:"44",
        question:"",
        src:"img/full/Screenshot_67.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },
    {
        id:"45",
        question:"",
        src:"img/full/Screenshot_68.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"4"
    },
    {
        id:"46",
        question:"",
        src:"img/full/Screenshot_69.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"4"
    },
    {
        id:"47",
        question:"",
        src:"img/full/Screenshot_70.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"1"
    },
    {
        id:"48",
        question:"",
        src:"img/full/Screenshot_71.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"2"
    },
    {
        id:"49",
        question:"",
        src:"img/full/Screenshot_72.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },
    {
        id:"50",
        question:"",
        src:"img/full/Screenshot_73.png",
        option1:"A",
        option2:"B",
        option3:"C",
        option4:"D",
        ansid:"3"
    },
    {
        id:"51",
        question:"you can submit your test!",
        src:"",
        option1:" ",
        option2:" ",
        option3:" ",
        option4:"",
        ansid:"5"
    }

    ];